export const GET_VOUCHER_REQUEST="GET_VOUCHER_REQUEST";
export const GET_VOUCHER_SUCCESS="GET_VOUCHER_SUCCESS";
export const GET_VOUCHER_ERROR="GET_VOUCHER_ERROR";

export const UPDATE_VOUCHER_REQUEST="UPDATE_VOUCHER_REQUEST";
export const UPDATE_VOUCHER_SUCCESS="UPDATE_VOUCHER_SUCCESS";
export const UPDATE_VOUCHER_ERROR="UPDATE_VOUCHER_ERROR";
