export const GET_VOUCHER_REQUEST="GET_VOUCHER_REQUEST";
export const GET_VOUCHER_SUCCESS="GET_VOUCHER_SUCCESS";
export const GET_VOUCHER_ERROR="GET_VOUCHER_ERROR";

export const UPDATE_VOUCHER_REQUEST="UPDATE_VOUCHER_REQUEST";
export const UPDATE_VOUCHER_SUCCESS="UPDATE_VOUCHER_SUCCESS";
export const UPDATE_VOUCHER_ERROR="UPDATE_VOUCHER_ERROR";

export const DELETE_VOUCHER_REQUEST=" DELETE_VOUCHER_REQUEST";
export const DELETE_VOUCHER_SUCCESS=" DELETE_VOUCHER_SUCCESS";
export const DELETE_VOUCHER_ERROR=" DELETE_VOUCHER_ERROR";

export const ADD_VOUCHER_REQUEST="ADD_VOUCHER_REQUEST";
export const ADD_VOUCHER_SUCCESS="ADD_VOUCHER_SUCCESS";
export const ADD_VOUCHER_ERROR="ADD_VOUCHER_ERROR";

export const GET_SINGLE_VOUCHER="GET_SINGLE_VOUCHER";



