export const GET_QUESTION_REQUEST = "GET_QUESTION_REQUEST";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_ERROR = "GET_QUESTION_ERROR";

export const ADD_QUESTION_REQUEST = "GET_QUESTION_REQUEST";
export const ADD_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS"
export const ADD_QUESTION_ERROR = "GET_QUESTION_ERROR"