export const GET_QUESTION_REQUEST = "GET_QUESTION_REQUEST";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_ERROR = "GET_QUESTION_ERROR";

export const ADD_QUESTION_REQUEST = "GET_QUESTION_REQUEST";
export const ADD_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS"
export const ADD_QUESTION_ERROR = "GET_QUESTION_ERROR"

export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const Update_QUESTION_ERROR = "UPDATE_QUESTION_ERROR";
