//student module action type
export const GET_STUDENT_REQUEST="GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS="GET_STUDENT_SUCCESS";
export const GET_STUDENT_ERROR="GET_STUDENT_ERROR";

export const ADD_STUDENT_REQUEST="ADD_STUDENT_REQUEST";
export const ADD_STUDENT_SUCCESS="ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR="ADD_STUDENT_ERROR";

export const UPDATE_STUDENT_REQUEST="UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS="UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_ERROR="UPDATE_STUDENT_ERROR";

export const DELETE_STUDENT_REQUEST="DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS="DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_ERROR="DELETE_STUDENT_ERROR";

export const GET_SINGLE_STUDENT="GET_SINGLE_STUDENT"