export const GET_FEEDBACK_REQUEST=" GET_FEEDBACK_REQUEST";
export const GET_FEEDBACK_SUCCESS=" GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_ERROR=" GET_FEEDBACK_ERROR";

export const ADD_FEEDBACK_REQUEST="ADD_FEEDBACK_REQUEST";
export const ADD_FEEDBACK_SUCCESS="ADD_FEEDBACK_SUCCESS";
export const ADD_FEEDBACK_ERROR="ADD_FEEDBACK_ERROR";

export const UPDATE_FEEDBACK_REQUEST="UPDATE_FEEDBACK_REQUEST";
export const UPDATE_FEEDBACK_SUCCESS="UPDATE_FEEDBACK_SUCCESS";
export const UPDATE_FEEDBACK_ERROR="UPDATE_FEEDBACK_ERROR";

export const GET_SINGLE_FEEDBACK=" GETGET_SINGLE_FEEDBACK";


export const DELETE_FEEDBACK_REQUEST=" DELETE_FEEDBACK_REQUEST";
export const DELETE_FEEDBACK_SUCCESS=" DELETE_FEEDBACK_SUCCESS";
export const DELETE_FEEDBACK_ERROR=" DELETE_FEEDBACK_ERROR";
