export const GET_FEEDBACK_REQUEST=" GET_FEEDBACK_REQUEST";
export const GET_FEEDBACK_SUCCESS=" GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_ERROR=" GET_FEEDBACK_ERROR";

export const ADD_FEEDBACK_REQUEST="ADD_FEEDBACK_REQUEST";
export const ADD_FEEDBACK_SUCCESS="ADD_FEEDBACK_SUCCESS";
export const ADD_FEEDBACK_ERROR="ADD_FEEDBACK_ERROR";
