//exam module action type
export const GET_EXAM_REQUEST="GET_EXAM_REQUEST";
export const GET_EXAM_SUCCESS="GET_EXAM_SUCCESS";
export const GET_EXAM_ERROR="GET_EXAM_ERROR";

export const ADD_EXAM_REQUEST="ADD_EXAM_REQUEST";
export const ADD_EXAM_SUCCESS="ADD_EXAM_SUCCESS";
export const ADD_EXAM_ERROR="ADD_EXAM_ERROR";

export const UPDATE_EXAM_REQUEST="UPDATE_EXAM_REQUEST";
export const UPDATE_EXAM_SUCCESS="UPDATE_EXAM_SUCCESS";
export const UPDATE_EXAM_ERROR="UPDATE_EXAM_ERROR";

export const DELETE_EXAM_REQUEST="DELETE_EXAM_REQUEST";
export const DELETE_EXAM_SUCCESS="DELETE_EXAM_SUCCESS";
export const DELETE_EXAM_ERROR="DELETE_EXAM_ERROR";

export const GET_SINGLE_EXAM="GET_SINGLE_EXAM"